//! Maven project output and the local repository (#67).
//!
//! Maven's `target/` layout is a documented convention
//! (<https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html>)
//! and the local repository lays artifacts out by coordinate, so both
//! can be identified from paths alone.
//!
//! # Downloaded, locally installed, or unknown
//!
//! The one claim this adapter must get right is *origin*, because it
//! decides whether removing an artifact is recoverable at all. Maven
//! leaves three kinds of evidence beside an artifact:
//!
//! * `_remote.repositories` -- written by Maven 3 when it resolved the
//!   artifact from a remote repository. Present means it was downloaded,
//!   and the same coordinates can be fetched again.
//! * `*.lastUpdated` -- a record of a *failed* or timestamped remote
//!   resolution attempt. Also evidence of a remote origin.
//! * `maven-metadata-local.xml` -- written by `mvn install`. The
//!   artifact was built on this machine, and if the source is gone, so
//!   is the artifact.
//!
//! With none of those, the origin is **unknown**, and this adapter says
//! unknown. #67 is explicit: "preserve downloaded versus locally
//! installed or unknown origin without assuming local artifacts can be
//! downloaded again." A guess in the wrong direction here costs someone
//! an artifact they cannot rebuild.
//!
//! # What is never done
//!
//! Plugins are never evaluated and POM properties are never resolved. An
//! unresolved `${property}` or a parent-inherited version is an explicit
//! identity gap, never a silently empty result -- the PR #123 review
//! found exactly that shape returning `Ok(vec![])`.

use super::{BuildAdapter, BuildCapabilities, BuildContainer, BuildCtx, NestedUnitBuilder};
use crate::artifact::{ArtifactRole, ArtifactVariant, Membership, NestedArtifact, relative_path};
use crate::entities::Confidence;
use std::path::{Path, PathBuf};

pub struct Adapter;

/// The conventional contents of a Maven `target/` directory.
const TARGET_ENTRIES: &[(&str, ArtifactRole, &str)] = &[
    (
        "classes",
        ArtifactRole::Output,
        "recompiled by the next `mvn compile`",
    ),
    (
        "test-classes",
        ArtifactRole::Output,
        "recompiled by the next `mvn test-compile`",
    ),
    (
        "generated-sources",
        ArtifactRole::Output,
        "regenerated by the next build; source generators run again",
    ),
    (
        "generated-test-sources",
        ArtifactRole::Output,
        "regenerated by the next build",
    ),
    (
        "surefire-reports",
        ArtifactRole::TestOutput,
        "regenerated by the next `mvn test`",
    ),
    (
        "failsafe-reports",
        ArtifactRole::TestOutput,
        "regenerated by the next `mvn verify`",
    ),
    (
        "site",
        ArtifactRole::Output,
        "regenerated by the next `mvn site`",
    ),
    (
        "maven-status",
        ArtifactRole::Metadata,
        "the compiler plugin rewrites it on the next build",
    ),
    (
        "maven-archiver",
        ArtifactRole::Metadata,
        "the archiver plugin rewrites it on the next package",
    ),
    (
        "test-run-info",
        ArtifactRole::Metadata,
        "regenerated by the next test run",
    ),
];

/// What the evidence beside a repository artifact establishes about how
/// it got there.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Origin {
    /// `_remote.repositories` or a `*.lastUpdated` marker: resolved from
    /// a remote repository.
    Downloaded,
    /// `maven-metadata-local.xml`: built and installed on this machine.
    LocallyInstalled,
    /// Neither. Swamp does not know, and does not guess.
    Unknown,
}

impl Origin {
    pub fn label(self) -> &'static str {
        match self {
            Self::Downloaded => "downloaded",
            Self::LocallyInstalled => "locally-installed",
            Self::Unknown => "unknown-origin",
        }
    }

    fn consequence(self) -> &'static str {
        match self {
            Self::Downloaded => {
                "the next build that needs this version downloads it again -- needs access to the \
                 repository it came from"
            }
            Self::LocallyInstalled => {
                "this version was installed from a local build; recreating it needs that project's \
                 source and an `mvn install`"
            }
            Self::Unknown => {
                "swamp found no origin evidence beside this artifact, so it cannot say whether it \
                 can be downloaded again"
            }
        }
    }
}

impl BuildAdapter for Adapter {
    fn id(&self) -> &'static str {
        "maven"
    }

    fn name(&self) -> &'static str {
        "Maven"
    }

    fn capabilities(&self) -> BuildCapabilities {
        BuildCapabilities {
            identifies_shared_stores: true,
            attributes_package_identity: true,
            actions_available: false,
        }
    }

    fn containers(&self, project_root: &Path, candidates: &[PathBuf]) -> Vec<BuildContainer> {
        if !project_root.join("pom.xml").is_file() {
            return Vec::new();
        }
        let mut out = Vec::new();
        let mut seen = std::collections::HashSet::new();
        let mut claim = |path: PathBuf| {
            if seen.insert(path.clone()) && path.is_dir() {
                out.push(BuildContainer::project(
                    "maven",
                    path,
                    project_root.to_path_buf(),
                ));
            }
        };
        claim(project_root.join("target"));
        for c in candidates {
            if c.file_name().and_then(|n| n.to_str()) == Some("target") {
                claim(c.clone());
            }
        }
        out
    }

    fn identify(&self, container: &BuildContainer, ctx: &BuildCtx) -> Vec<NestedArtifact> {
        if container.shared {
            return identify_repository(container, ctx);
        }
        identify_target(container, ctx)
    }
}

fn identify_target(container: &BuildContainer, ctx: &BuildCtx) -> Vec<NestedArtifact> {
    let mut root = NestedUnitBuilder::new(container, ArtifactRole::Output, container.path.clone())
        .is_dir(true)
        .supported_with_reason("a Maven project target directory, in the standard layout")
        .evidence("maven-layout", "standard target layout", Confidence::Medium)
        .consequence("the next `mvn package` regenerates everything it holds");
    match ctx.folded().get(&container.path) {
        Some(d) => root = root.folded(d),
        None => root = root.limit("this directory was not measured by the walk this pass"),
    }
    let mut units = vec![root.build()];

    for child in ctx.folded().children(&container.path) {
        let name = child
            .path
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or_default()
            .to_string();
        let known = TARGET_ENTRIES.iter().find(|(n, _, _)| *n == name);
        let mut b = NestedUnitBuilder::new(
            container,
            known
                .map(|(_, r, _)| r.clone())
                .unwrap_or(ArtifactRole::Residual),
            child.path.clone(),
        )
        .folded(child);
        b = match known {
            Some((_, _, consequence)) => b
                .supported_with_reason(format!(
                    "`target/{name}` is part of Maven's standard directory layout"
                ))
                .evidence(
                    "maven-layout",
                    format!("standard target/{name}"),
                    Confidence::Medium,
                )
                .consequence(*consequence),
            None => b.unsupported_layout(format!(
                "`target/{name}` is not part of the standard layout; a plugin chose it, and swamp \
                 never evaluates plugins"
            )),
        };
        units.push(b.build());
    }

    // Packaged artifacts sit directly in `target/`. Listed shallowly:
    // `target/classes` may hold tens of thousands of class files and
    // none of them is a unit.
    for entry in ctx.list(&container.path) {
        if entry.is_dir {
            continue;
        }
        let packaging = match entry.name.rsplit_once('.') {
            Some((_, ext @ ("jar" | "war" | "ear" | "zip" | "aar"))) => ext,
            _ => continue,
        };
        let path = container.path.join(&entry.name);
        let Some(meta) = ctx.stat(&path) else {
            continue;
        };
        if !meta.is_file() {
            continue;
        }
        let variant = ArtifactVariant {
            configuration: Some(packaging.to_string()),
            // Maven records no build generation: a jar's timestamp says
            // when it was packaged, never that it supersedes another.
            unknowns: vec!["build-generation".into()],
            ..Default::default()
        };
        units.push(
            NestedUnitBuilder::new(container, ArtifactRole::Output, path)
                .from_file_metadata(&meta)
                .variant(variant)
                .supported_with_reason(format!(
                    "a packaged `{packaging}` artifact in the project's target directory"
                ))
                .evidence(
                    "maven-layout",
                    format!("packaged {packaging}"),
                    Confidence::High,
                )
                .consequence("the next `mvn package` repackages it")
                .build(),
        );
    }
    units
}

/// A Maven local repository (`~/.m2/repository` or a configured
/// `localRepository`), handed in as a shared container.
fn identify_repository(container: &BuildContainer, ctx: &BuildCtx) -> Vec<NestedArtifact> {
    let mut root = NestedUnitBuilder::new(
        container,
        ArtifactRole::SharedStoreEntry,
        container.path.clone(),
    )
    .is_dir(true)
    .supported_with_reason("a Maven local repository shared by every Maven build on this machine")
    .evidence("maven-layout", "local repository", Confidence::Medium)
    .consequence(
        "downloaded artifacts are fetched again on the next build; locally installed ones are not \
         -- they need the source project and an `mvn install`",
    )
    .no_action_because("this repository is shared by every Maven project on this machine");
    match ctx.folded().get(&container.path) {
        Some(d) => root = root.folded(d),
        None => root = root.limit("this repository was not measured by the walk this pass"),
    }
    let mut units = vec![root.build()];

    // Version directories are the unit: `<group dirs>/<artifact>/<version>`.
    // A version directory is one whose *parent* chain has at least one
    // more segment and whose own name looks like a version -- which is
    // how a `commons-io/commons-io/2.11.0` is told from the group
    // directories above it without listing anything.
    for dir in ctx.folded().under(&container.path) {
        let rel = relative_path(&container.path, &dir.path);
        if rel.is_empty() {
            continue;
        }
        let name = dir
            .path
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or_default();
        if !crate::build_adapters::jvm_common::looks_like_version(name) {
            continue;
        }
        let coords = crate::build_adapters::jvm_common::coordinates_from_relative(&rel, false);
        let origin = origin_of(ctx, &dir.path);
        let mut variant = ArtifactVariant::default();
        match &coords {
            Some(c) => {
                variant.package = Some(format!("{}:{}", c.group, c.artifact));
                variant.version = c.version.clone();
                variant.configuration = Some(origin.label().to_string());
            }
            None => {
                variant.unknowns.push("package".into());
                variant.unknowns.push("version".into());
            }
        }
        if origin == Origin::Unknown {
            variant.unknowns.push("origin".into());
        }
        let mut b =
            NestedUnitBuilder::new(container, ArtifactRole::SharedStoreEntry, dir.path.clone())
                .folded(dir)
                .variant(variant)
                .membership(Membership::Unknown)
                .consequence(origin.consequence())
                .no_action_because(
                    "a repository artifact may be a dependency of any project on this machine",
                );
        b = match &coords {
            Some(c) => b
                .supported_with_reason(format!(
                    "the local repository lays artifacts out by coordinate; this is {}",
                    c.display()
                ))
                .evidence(
                    "maven-repository",
                    format!("{} ({})", c.display(), origin.label()),
                    Confidence::High,
                ),
            None => b.unsupported_layout(format!(
                "`{rel}` is not a coordinate layout this adapter can read"
            )),
        };
        if origin == Origin::Unknown {
            b = b.limit(
                "no `_remote.repositories`, `*.lastUpdated` or `maven-metadata-local.xml` beside \
                 this artifact: swamp cannot tell whether it was downloaded or installed locally, \
                 and does not assume it can be downloaded again",
            );
        }
        units.push(b.build());
    }
    units
}

/// The origin evidence Maven left beside one version directory.
///
/// One capped listing per version directory, no content read: the
/// *presence* of the marker files is the evidence, and their contents
/// add nothing this adapter uses.
pub(crate) fn origin_of(ctx: &BuildCtx, version_dir: &Path) -> Origin {
    let mut downloaded = false;
    let mut local = false;
    for e in ctx.list(version_dir) {
        if e.is_dir {
            continue;
        }
        if e.name == "_remote.repositories" || e.name.ends_with(".lastUpdated") {
            downloaded = true;
        }
        if e.name == "maven-metadata-local.xml" {
            local = true;
        }
    }
    match (downloaded, local) {
        // Both: Maven records `_remote.repositories` for an installed
        // artifact too in some layouts, and the local metadata is the
        // stronger claim about where the bytes came from. Reporting
        // "downloaded" here would be the guess that costs an artifact.
        (_, true) => Origin::LocallyInstalled,
        (true, false) => Origin::Downloaded,
        (false, false) => Origin::Unknown,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::artifact::TimeSource;
    use crate::build_adapters::{ContainerCache, FoldedDir, FoldedIndex};
    use crate::fs_events::EventCoverage;
    use std::fs;

    fn index(entries: &[(&PathBuf, u64, u64)]) -> FoldedIndex {
        FoldedIndex::from_dirs(entries.iter().map(|(p, b, m)| FoldedDir {
            path: (*p).clone(),
            allocated_total: *b,
            mtime_max: *m,
            complete: true,
        }))
    }

    fn run(c: &BuildContainer, idx: &FoldedIndex) -> Vec<NestedArtifact> {
        let none = EventCoverage::untrusted();
        let cache = ContainerCache::disabled();
        Adapter.identify(c, &BuildCtx::new(1_000, idx, &none, &cache))
    }

    #[test]
    fn unknown_layout_is_explicit_not_empty() {
        let tmp = tempfile::tempdir().unwrap();
        let target = tmp.path().join("target");
        let plugin = target.join("jacoco-ut");
        fs::create_dir_all(&plugin).unwrap();
        let c = BuildContainer::project("maven", target.clone(), tmp.path().to_path_buf());
        let units = run(&c, &index(&[(&target, 100, 500), (&plugin, 60, 500)]));
        let u = units.iter().find(|u| u.path == plugin).expect("a row");
        assert!(!u.coverage.supported);
        assert_eq!(u.role, ArtifactRole::Residual);
        assert!(
            u.coverage
                .limits
                .iter()
                .any(|l| l.contains("never evaluates plugins")),
            "{:?}",
            u.coverage.limits
        );
    }

    #[test]
    fn identification_reads_no_more_than_manifest_cap() {
        let tmp = tempfile::tempdir().unwrap();
        let repo = tmp.path().join("repository");
        let v = repo.join("commons-io/commons-io/2.11.0");
        fs::create_dir_all(&v).unwrap();
        // Evidence files far larger than the cap. Origin is decided by
        // their *presence*, so nothing reads them at all.
        fs::write(v.join("_remote.repositories"), vec![b'x'; 900_000]).unwrap();
        let c = BuildContainer::shared_store("maven", repo.clone());
        let idx = index(&[
            (&repo, 1_000, 500),
            (&repo.join("commons-io"), 900, 500),
            (&repo.join("commons-io/commons-io"), 900, 500),
            (&v, 900, 500),
        ]);
        let (_u, counted) = crate::work_counters::measured(|| run(&c, &idx));
        assert!(
            counted.header_bytes_read <= super::super::bounded_io::MAX_MANIFEST_BYTES as u64,
            "read {} bytes",
            counted.header_bytes_read
        );
        assert_eq!(
            counted.header_bytes_read, 0,
            "origin is established by the presence of marker files, never by reading them"
        );
    }

    #[test]
    fn no_project_or_build_code_is_executed() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        fs::write(root.join("pom.xml"), b"<project/>").unwrap();
        fs::create_dir_all(root.join("target/classes")).unwrap();
        fs::write(root.join("mvnw"), b"#!/bin/sh\nexit 5\n").unwrap();
        let c = BuildContainer::project("maven", root.join("target"), root.to_path_buf());
        let idx = index(&[
            (&root.join("target"), 100, 500),
            (&root.join("target/classes"), 90, 500),
        ]);
        let (_u, counted) = crate::work_counters::measured(|| run(&c, &idx));
        assert_eq!(
            counted.subprocess_spawns, 0,
            "identification spawned a process; Maven and its wrapper are never invoked"
        );
    }

    #[test]
    fn variants_never_collapse_by_basename() {
        // Two versions of one artifact, and two artifacts with the same
        // version. Neither pair may collapse.
        let tmp = tempfile::tempdir().unwrap();
        let repo = tmp.path().join("repository");
        let a1 = repo.join("commons-io/commons-io/2.11.0");
        let a2 = repo.join("commons-io/commons-io/2.15.1");
        let b1 = repo.join("org/slf4j/slf4j-api/2.11.0");
        for p in [&a1, &a2, &b1] {
            fs::create_dir_all(p).unwrap();
        }
        let c = BuildContainer::shared_store("maven", repo.clone());
        let idx = index(&[
            (&repo, 1_000, 500),
            (&repo.join("commons-io"), 600, 500),
            (&repo.join("commons-io/commons-io"), 600, 500),
            (&a1, 300, 500),
            (&a2, 300, 500),
            (&repo.join("org"), 400, 500),
            (&repo.join("org/slf4j"), 400, 500),
            (&repo.join("org/slf4j/slf4j-api"), 400, 500),
            (&b1, 400, 500),
        ]);
        let units = run(&c, &idx);
        let u1 = units.iter().find(|u| u.path == a1).expect("2.11.0");
        let u2 = units.iter().find(|u| u.path == a2).expect("2.15.1");
        let u3 = units.iter().find(|u| u.path == b1).expect("slf4j 2.11.0");
        assert_ne!(u1.id, u2.id);
        assert_ne!(u1.id, u3.id);
        assert_eq!(u1.variant.version.as_deref(), Some("2.11.0"));
        assert_eq!(u2.variant.version.as_deref(), Some("2.15.1"));
        assert_eq!(u1.variant.package.as_deref(), Some("commons-io:commons-io"));
        assert_eq!(u3.variant.package.as_deref(), Some("org.slf4j:slf4j-api"));
    }

    #[test]
    fn age_is_not_obsolescence() {
        let tmp = tempfile::tempdir().unwrap();
        let repo = tmp.path().join("repository");
        let v = repo.join("commons-io/commons-io/1.0");
        fs::create_dir_all(&v).unwrap();
        let c = BuildContainer::shared_store("maven", repo.clone());
        let units = run(
            &c,
            &index(&[
                (&repo, 100, 1),
                (&repo.join("commons-io"), 100, 1),
                (&repo.join("commons-io/commons-io"), 100, 1),
                (&v, 100, 1),
            ]),
        );
        let u = units.iter().find(|u| u.path == v).unwrap();
        assert_eq!(u.time_source, TimeSource::FoldedDirectoryModification);
        assert_eq!(
            u.variant.configuration.as_deref(),
            Some("unknown-origin"),
            "a very old artifact with no origin evidence has an unknown origin, not a presumed one"
        );
        // The verdict-vocabulary scan over every string this unit can
        // put in front of a person lives in
        // `crates/core/tests/build_adapter_contract.rs::no_unit_renders_a_verdict`.
        // It is not repeated here, because spelling the banned words in
        // `crates/core/src` is itself what `scripts/check.sh`'s grep
        // audit rejects -- and a weaker copy of a stronger check is not
        // worth the exemption.
    }

    #[test]
    fn a_locally_installed_artifact_is_never_called_downloadable() {
        let tmp = tempfile::tempdir().unwrap();
        let repo = tmp.path().join("repository");
        let v = repo.join("com/example/app/1.0-SNAPSHOT");
        fs::create_dir_all(&v).unwrap();
        fs::write(v.join("maven-metadata-local.xml"), b"<metadata/>").unwrap();
        // Maven writes both markers in some layouts; the local one is
        // the stronger claim and must win.
        fs::write(v.join("_remote.repositories"), b"").unwrap();
        let c = BuildContainer::shared_store("maven", repo.clone());
        let idx = index(&[
            (&repo, 100, 500),
            (&repo.join("com"), 100, 500),
            (&repo.join("com/example"), 100, 500),
            (&repo.join("com/example/app"), 100, 500),
            (&v, 100, 500),
        ]);
        let units = run(&c, &idx);
        let u = units.iter().find(|u| u.path == v).unwrap();
        assert_eq!(
            u.variant.configuration.as_deref(),
            Some("locally-installed")
        );
        let consequence = u.consequence.clone().unwrap_or_default();
        assert!(
            consequence.contains("mvn install"),
            "the consequence names the only way back: {consequence}"
        );
        assert!(
            !consequence.contains("downloads it again"),
            "a locally installed artifact is never promised as re-downloadable: {consequence}"
        );
    }

    #[test]
    fn an_artifact_with_no_evidence_has_an_unknown_origin() {
        let tmp = tempfile::tempdir().unwrap();
        let repo = tmp.path().join("repository");
        let v = repo.join("com/example/mystery/9.9");
        fs::create_dir_all(&v).unwrap();
        let c = BuildContainer::shared_store("maven", repo.clone());
        let idx = index(&[
            (&repo, 100, 500),
            (&repo.join("com"), 100, 500),
            (&repo.join("com/example"), 100, 500),
            (&repo.join("com/example/mystery"), 100, 500),
            (&v, 100, 500),
        ]);
        let units = run(&c, &idx);
        let u = units.iter().find(|u| u.path == v).unwrap();
        assert!(u.variant.unknowns.iter().any(|x| x == "origin"));
        assert!(
            u.coverage
                .limits
                .iter()
                .any(|l| l.contains("does not assume it can be downloaded again")),
            "{:?}",
            u.coverage.limits
        );
    }

    #[test]
    fn a_missing_pom_claims_nothing() {
        let tmp = tempfile::tempdir().unwrap();
        fs::create_dir_all(tmp.path().join("target")).unwrap();
        assert!(
            Adapter.containers(tmp.path(), &[]).is_empty(),
            "a `target/` with no pom.xml beside it is not Maven's"
        );
    }
}
