[package]
name = "swamp-core"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
async-trait.workspace = true
futures-util.workspace = true
anyhow.workspace = true
libc = "0.2"
toml.workspace = true
zstd = "0.13"
arrow-array.workspace = true
arrow-schema.workspace = true
blake3.workspace = true
gix = { version = "0.87", default-features = false, features = ["max-performance-safe", "status", "revision", "sha1"] }
parquet.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
tempfile.workspace = true
roxmltree = "0.21.1"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10.1"
core-foundation-sys = "0.8.7"
fsevent-sys = "5.2.0"
