[package]
name = "slop-livin-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
blake3.workspace = true
gix = { version = "0.87", default-features = false, features = ["max-performance-safe", "status", "revision", "sha1"] }
parquet.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10.1"
core-foundation-sys = "0.8.7"
fsevent-sys = "5.2.0"
